開発用のプロジェクトを作る
extreal-dev/Extreal.SampleApp.Holiday pull request #1
Opened 2022-10-31 02:09 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- 3D（URP）テンプレートで作成

# What did you verify? (何を確認しましたか?)

- [ ] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [ ] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [ ] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [ ] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [ ] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

2022-11-14 07:25 UTC, sus-taguchi-t requested changes

2022-11-14 07:25 UTC, sus-taguchi-t commented on Assets/Holiday/Stages/LoadingScreen/LoadingScreenPresenter.cs
> +        }
ここではおそらくローディング中に画面がぶれないようにローディング画面を 200us だけ見せて制御しているのだと思います。
しかし Unity の仕様上これだけでは不十分で、このままだとバーチャル空間の UI がローディング画面の上に出現してしまいます。
これを防ぐためには Unity Editor の LoadingScreen シーンで ScreenCanvas 内の Canvas コンポーネントの SortOeder を 0 より大きい値に設定します。
SortOrder は小さい順に描画されて、大きいほど手前に描画されます。

BackgroundScene についても考え方は同様です。

2022-11-15 01:46 UTC, kiyohome commented on Assets/Holiday/App/AppInitializer.cs
> +    using UnityEngine;
editorconfigを修正して外にします。
多くのライブラリが外なので。

2022-11-15 01:51 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +            builder.Register<Player>(Lifetime.Singleton);
すみません、消します。

2022-11-15 01:52 UTC, kiyohome commented on Assets/Holiday/App/SceneName.cs
> +    }
作っていった順番です。

2022-11-15 01:52 UTC, kiyohome commented on Assets/Holiday/Models/Player.cs
> +    public class Player : MonoBehaviour
消します。

2022-11-15 01:54 UTC, kiyohome commented on Assets/Holiday/Models/Player.cs
> +        private new readonly ReactiveProperty<string> name = new();
editorconfigの設定で外しましょう。

2022-11-15 01:56 UTC, kiyohome commented on Assets/Holiday/Models/Player.cs
> +        public Transform CameraRoot => player.gameObject.transform.Find("PlayerCameraRoot");
.gameObjectは削除します。
player のnullチェックはインタフェースが悪いかもなので見直します。

2022-11-15 02:02 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +            builder.RegisterInstance(stageConfig).AsImplementedInterfaces();
RegisterComponentに統一しましょう。

2022-11-15 02:02 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +            builder.RegisterInstance(stageConfig).AsImplementedInterfaces();
追加でBannedApiAnalyzersを入れましょう。

2022-11-15 02:07 UTC, kiyohome commented on Assets/Holiday/Stages/AvatarSelectionScreen/AvatarSelectionScreenView.cs
> +        private readonly List<string> avatarNames = new List<string>();
インデックスでなく、値を返したいのでこうしてます。

2022-11-15 04:53 UTC, sus-taguchi-t commented on Assets/Holiday/Stages/AvatarSelectionScreen/AvatarSelectionScreenView.cs
> +        private readonly List<string> avatarNames = new List<string>();
ここではあまり処理速度が問題にならなそうなのでこのままでいきましょう。

2022-11-15 04:54 UTC, sus-taguchi-t commented on Assets/Holiday/Stages/Common/SafeAreaView.cs
> +    }
分かりました。
このままでお願いします。

2022-11-26 01:23 UTC, kiyohome commented on Assets/Holiday/App/AppInitializer.cs
> +    using UnityEngine;
修正しました！
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/1/commits/a831a34728c42efc7deaacfda24a5f5efb711f80

2022-11-29 13:53 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +            builder.Register<Player>(Lifetime.Singleton);
消しました！
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/1/commits/1e56049c41407c09d81b91d388a9b47f8bde2fa1

2022-11-29 14:37 UTC, kiyohome commented on Assets/Holiday/Models/Player.cs
> +    public class Player : MonoBehaviour
消しました
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/1/commits/8765a2474fe03d23b85ee90a3c57e48fb72abf44

2022-11-29 14:52 UTC, kiyohome commented on Assets/Holiday/Models/Player.cs
> +        private new readonly ReactiveProperty<string> name = new();
修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/1/commits/3ac9d9840a69ee4a9fc20b9161d050455eb04280

2022-11-29 14:56 UTC, kiyohome commented on Assets/Holiday/Models/Player.cs
> +        }
AvatarRepositoryから取得した値を初期値に使ってる部分があるので、まとめて一ヶ所で設定してます。

2022-11-29 15:02 UTC, kiyohome commented on Assets/Holiday/Models/Player.cs
> +        public Transform CameraRoot => player.gameObject.transform.Find("PlayerCameraRoot");
対応しました
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/1/commits/32cbb9b4b89ebec1b6640ec4d643377137dd2a93

2022-11-29 15:07 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +            builder.RegisterInstance(stageConfig).AsImplementedInterfaces();
RegisterComponentに修正
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/1/commits/c1a0704088869e57371a81bdbf0abfa430c74278

2022-11-29 15:09 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +            builder.RegisterInstance(stageConfig).AsImplementedInterfaces();
BannedApiAnalyzersはすぐにできそうにないのでPBIに入れました。

2022-11-30 02:03 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppInitializer.cs
> +    using UnityEngine;
確認しました！

2022-11-30 02:04 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +            builder.Register<Player>(Lifetime.Singleton);
確認しました！

2022-11-30 02:06 UTC, sus-taguchi-t commented on Assets/Holiday/App/SceneName.cs
> +    }
分かりました。

2022-11-30 02:15 UTC, sus-taguchi-t commented on Assets/Holiday/Models/Player.cs
> +    public class Player : MonoBehaviour
確認しました！

2022-11-30 02:18 UTC, sus-taguchi-t commented on Assets/Holiday/Models/Player.cs
> +        }
分かりました。

2022-11-30 02:22 UTC, sus-taguchi-t commented on Assets/Holiday/Models/Player.cs
> +        public Transform CameraRoot => player.gameObject.transform.Find("PlayerCameraRoot");
確認しました！

2022-11-30 02:27 UTC, sus-taguchi-t commented on Assets/Holiday/Stages/LoadingScreen/LoadingScreenPresenter.cs
> +        }
確認しました！

2022-11-30 02:28 UTC, sus-taguchi-t approved these changes

2022-11-30 02:28 UTC, merged