P2 p
extreal-dev/Extreal.SampleApp.Holiday pull request #11
Opened 2023-07-06 01:28 UTC by kiyohome

# 何の変更を加えましたか？

- [ ] 

# 何を確認しましたか?

## 実装
- [ ] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました

## テスト
- [ ] 変更影響がある全てのテストが成功することを確認しました
- [ ] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響
- [ ] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-08-21 12:51 UTC, sus-taguchi-t requested changes

2023-08-21 12:51 UTC, sus-taguchi-t commented on .gitignore
> +WebGLBuild/Data
`WebGLBuild/Holiday/*` `WebGLBuild/Data/*` のようにした方が良いと思います。

2023-08-21 12:51 UTC, sus-taguchi-t commented on .vscode/settings.json
> +    "./Assets/Servers/P2P",
`./Servers/P2P` ではないでしょうか？

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +            multiplayReady.Merge(textChatReady, voiceChatReady, spaceReady, p2PReady)
ここは `MultiplayControl` のように `Observable.CombineLatest` にしないのでしょうか？

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +                Logger.LogDebug($"Space, P2P, Multiplay, TextChat, VoiceChat, Space Ready: "
`Space` が 2 回存在しています。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +        private readonly Subject<Message> onMessageReceived = new Subject<Message>();
`Message` 関連はまだ使用していませんが、この PR に含めますか？

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/App/AssetWorkflow/Custom/CryptoAssetBundleProvider.cs
こちらの削除と Addressables のダウンロード URL を保持する場所の変更に合わせて `SecretVariables.cs` も不要になったので、Custom ディレクトリごと一緒に削除した方が良いと思います。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/App/Config/MessageConfig.cs
> +        [SerializeField] private string landscapeErrorMessage;
まだ Landscape の機能は存在しないと思いますが、この PR に含めますか？

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/ClientControl/ClientControlPresenter.cs
> +                .Where(_ => appState.IsClient)
ライブラリを修正したのでここの条件は不要です。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/Common/Multiplay/NetworkThirdPersonController.cs
> +            this.isTouchDevice = true;
`this.` は不要です。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlScope.cs
> +namespace Extreal.SampleApp.Holiday.Controls.MultiplyClientControl
ここは元の名前空間のままでいいと思います。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +namespace Extreal.SampleApp.Holiday.Holiday.Controls.P2PControl
`Holiday` が 2 回出現しています。
`Scope` も同様です。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/TextChatControl/TextChatControlPresenter.cs
> +                .AddTo(stageDisposables);
そもそも `textChatReady` は必要でしょうか？
`voiceChatReady` の必要性も併せて考えたいです。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +                stageNavigator.ReplaceAsync(StageName.GroupSelectionStage);
`CS4014` 番の静的解析が「'await' 演算子を適用することを検討」するように警告を出しています。
`.Forget()` メソッドをチェインさせた方が良いと思います。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/AvatarSelectionScreen/AvatarSelectionScreenPresenter.cs
> +                .Subscribe(_ => stageNavigator.ReplaceAsync(StageName.GroupSelectionStage))
`CS4014` 番の静的解析が「'await' 演算子を適用することを検討」するように警告を出しています。
`.Forget()` メソッドをチェインさせた方が良いと思います。

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                .Subscribe(async _ => await groupManager.UpdateGroupsAsync())
ここは同期にする必要があるのでしょうか？

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                        groups.Count > 0 ? groupManager.FindByName(groupNames.FirstOrDefault()).Id : null);
```suggestion
                        groups.Count > 0 ? groups.First().Id : null);
```

このようにしてはいけないのでしょうか？

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/WebGLScripts.meta
こちらと同様にディレクトリ名の末尾に `~` を付けた方が良いと思いました。
https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1#discussion_r1296903831

2023-08-21 12:51 UTC, sus-taguchi-t commented on Assets/WebGLTemplates/Holiday/index.js
このファイルはビルド生成物だと思うので gitignore して良いと思います。

2023-08-24 06:31 UTC, sasuke9410 commented on .gitignore
> +WebGLBuild/Data
Fixed 33f0a6b1bb95d905e0eb2573e1228e5ad8339805

2023-08-24 06:32 UTC, sasuke9410 commented on .vscode/settings.json
> +    "./Assets/Servers/P2P",
Fixed f888dd4a5b872c74f668ee62536b6f971b63a254

2023-08-24 07:35 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +                Logger.LogDebug($"Space, P2P, Multiplay, TextChat, VoiceChat, Space Ready: "
Fixed dc0c11bc05757ea6d13092adca82fc462a01f077

2023-08-24 09:46 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +        private readonly Subject<Message> onMessageReceived = new Subject<Message>();
今回のRPには含めず、Messageの使用時に宣言するようにします。
Fixed be0ecf2dff2860f3d76e7746c230f724f2040b59

2023-08-24 09:58 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +        private readonly Subject<Message> onMessageReceived = new Subject<Message>();
ReceivedMessageメソッドからonMessageReceivedが呼ばれており、
MultiplayClient.ReceivedFromEveryoneMessageHandlerからReceivedMessageメソッドが呼ばれているため
残す必要があると思っています。

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/App/AssetWorkflow/Custom/CryptoAssetBundleProvider.cs
Assets/Holiday/App/AssetWorkflow/Customディレクトリを指していると思っています、
このフォルダは今回のプルリクで削除されている認識のため、対応不要だと考えています。

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/App/Config/MessageConfig.cs
> +        [SerializeField] private string landscapeErrorMessage;
今回のPRには含めず、Landscape機能実装時に宣言するようにします。
Fixed f9393053c2d772912bbb21c936919e71645fb209

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Controls/Common/Multiplay/NetworkThirdPersonController.cs
> +            this.isTouchDevice = true;
Fixed b9d299009183030ff7a7138ea898bfbf92e70254

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlScope.cs
> +namespace Extreal.SampleApp.Holiday.Controls.MultiplyClientControl
Fixed c99867837d2bfe9f5b57aa95d54753dde3eec70d

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +namespace Extreal.SampleApp.Holiday.Holiday.Controls.P2PControl
Fixed a4deaca8db6808f60f6513f59ffb060891510617

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Screens/AvatarSelectionScreen/AvatarSelectionScreenPresenter.cs
> +                .Subscribe(_ => stageNavigator.ReplaceAsync(StageName.GroupSelectionStage))
Fixed b1ef5511d15f2c66d8c919895b5cafb223ca9544

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +                stageNavigator.ReplaceAsync(StageName.GroupSelectionStage);
Fixed b1ef5511d15f2c66d8c919895b5cafb223ca9544

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Controls/ClientControl/ClientControlPresenter.cs
> +                .Where(_ => appState.IsClient)
OnUnexpectedDisconnectedの発火タイミングがNgoClientクラス内にしかないため、Where句が不要な認識です。
Fixed 5c199188b753ac0deddb8c2dfad5995b54f11e58

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                        groups.Count > 0 ? groupManager.FindByName(groupNames.FirstOrDefault()).Id : null);
問題ないと考えたため指摘の通り修正しました。
Fixed 4f689114490add8b4519e2612f901eb071b6745b

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/WebGLTemplates/Holiday/index.js
yarnコマンド実行時に生成されることを確認出来たため不要
Fixed 0a3600de56ba92a0322e829773674900074f78cd

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/WebGLScripts.meta
ファイル名への~の付与、フォルダ内の.metaファイルの削除を行いました。
Fixed 2076fcbf48a3c3c183be0da92f39ea2e03935446

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                .Subscribe(async _ => await groupManager.UpdateGroupsAsync())
awaitを削除した場合、以下のワーニングが出ます。
```
この呼び出しは待機されないため、呼び出しが完了するまで現在のメソッドの実行は継続されます。
呼び出しの結果に 'await' 演算子を使用することを検討してください。
```
・呼び出しているホストのリスト取得処理は非同期にする必要があるほど時間のかかる処理ではない
・Subscribeメソッド内で非同期処理を呼ぶ場合、その後の処理がどうなるか不明瞭
であるため、同期処理のままでいいと考えています。

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/Controls/TextChatControl/TextChatControlPresenter.cs
> +                .AddTo(stageDisposables);
指摘の意図が掴み切れない部分があるため確認させてください。
textChatReady、voiceChatReadyに関して
・これら2つの状態はSpaceReady等と違いHolidayの動作に必須ではないため、Ready状態の管理は不要
・これら2つの状態を条件分岐等に使用していないため現状、定義する必要がない
　(例：チャットのテキストボックスはtextChatReadyの状態によって表示/非表示を切り替えるべきetc...)
・その他
のどれを指しているのでしょうか？

2023-08-29 02:29 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +            multiplayReady.Merge(textChatReady, voiceChatReady, spaceReady, p2PReady)
処理の内容は変わらない認識です。
MergeよりCombineLatestの方が最新状態を保持している分、
すこしだけ負荷がかかっていると考えられるためMergeでよく、修正不要だと判断しました。

2023-08-29 04:14 UTC, sasuke9410 commented on Assets/Holiday/Controls/TextChatControl/TextChatControlPresenter.cs
> +                .AddTo(stageDisposables);
textChatReadyとvoiceChatReadyが不要との判断になったため、
これらの宣言と処理部分を削除した
Fixed f3599c9865c14f454c73f0993b0544420e3c3df7

2023-09-01 00:05 UTC, sus-taguchi-t commented on .gitignore
> +WebGLBuild/Data
確認しました！

2023-09-01 00:07 UTC, sus-taguchi-t commented on .vscode/settings.json
> +    "./Assets/Servers/P2P",
確認しました！

2023-09-01 00:16 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +            multiplayReady.Merge(textChatReady, voiceChatReady, spaceReady, p2PReady)
そうであれば `MultiplayControl` の処理を `Merge` に修正した方が良いのではないのでしょうか？

2023-09-01 00:17 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +                Logger.LogDebug($"Space, P2P, Multiplay, TextChat, VoiceChat, Space Ready: "
`Ready` は残しておいた方が良いと思います。

2023-09-01 02:09 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +        private readonly Subject<Message> onMessageReceived = new Subject<Message>();
120 行目の `SendMessage` メソッドが使用されていないのでその先はすべて使用されていないと思っています。
コードカバレッジも通っていないと思いますが。

2023-09-01 02:14 UTC, sus-taguchi-t commented on Assets/Holiday/App/AssetWorkflow/Custom/CryptoAssetBundleProvider.cs
すみません、私の指摘ミスでした。

2023-09-01 02:14 UTC, sus-taguchi-t commented on Assets/Holiday/App/Config/MessageConfig.cs
> +        [SerializeField] private string landscapeErrorMessage;
確認しました！

2023-09-01 02:15 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/ClientControl/ClientControlPresenter.cs
> +                .Where(_ => appState.IsClient)
https://github.com/xr-campus-dev/BirdsEye/pull/6#pullrequestreview-1605972896

2023-09-01 02:17 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/ClientControl/ClientControlPresenter.cs
> +                .Where(_ => appState.IsClient)
確認しました！

2023-09-01 02:18 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/Common/Multiplay/NetworkThirdPersonController.cs
> +            this.isTouchDevice = true;
確認しました！

2023-09-01 02:18 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlScope.cs
> +namespace Extreal.SampleApp.Holiday.Controls.MultiplyClientControl
確認しました！

2023-09-01 02:18 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +namespace Extreal.SampleApp.Holiday.Holiday.Controls.P2PControl
確認しました！

2023-09-01 02:23 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/TextChatControl/TextChatControlPresenter.cs
> +                .AddTo(stageDisposables);
各クライアントの Presenter で `textChatClient.Clear()` と `voiceChatClient.Clear()` は残しておいた方が良いと思います。
また `AppState` の `LogWaitingStatus` メソッドでログを出力させているところから `TextChat, VoiceChat` の部分も削除した方が良いです。

2023-09-01 02:23 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +                stageNavigator.ReplaceAsync(StageName.GroupSelectionStage);
確認しました！

2023-09-01 02:24 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/AvatarSelectionScreen/AvatarSelectionScreenPresenter.cs
> +                .Subscribe(_ => stageNavigator.ReplaceAsync(StageName.GroupSelectionStage))
確認しました！

2023-09-01 02:27 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                .Subscribe(async _ => await groupManager.UpdateGroupsAsync())
そもそもこの処理を待つ必要がない上、例外のハンドリングを入れない限りは同期でも非同期でもその後の処理を気にしていないことに変わりがないため同期にする必要はないと考えています。
`await` を消した場合に出てくる警告に関しては `Forget` メソッドをチェインさせれば良いと思います。

2023-09-01 02:30 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                        groups.Count > 0 ? groupManager.FindByName(groupNames.FirstOrDefault()).Id : null);
確認しました！

2023-09-01 02:32 UTC, sus-taguchi-t commented on Assets/WebGLScripts.meta
ありがとうございます！
ただ `.gitignore` を変更していないため `node_modules` ディレクトリの中身がすべて push されてしまっています。
これも対応をお願いします。

2023-09-01 02:38 UTC, sus-taguchi-t commented on Assets/WebGLTemplates/Holiday/index.js
併せて `index.js.meta` の ignore もお願いします。

2023-09-01 02:40 UTC, sus-taguchi-t submitted a review, later dismissed

2023-09-01 02:40 UTC, sus-taguchi-t commented on .gitignore
>  SecretVariables.cs*
これらも不要です。

2023-09-06 09:03 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +                Logger.LogDebug($"Space, P2P, Multiplay, TextChat, VoiceChat, Space Ready: "
Fixed 180c6ce5f247ff6cc6ba2f28c18261af9acda7ca

2023-09-06 10:20 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +            multiplayReady.Merge(textChatReady, voiceChatReady, spaceReady, p2PReady)
自分の意見をひっくり返して申し訳ないのですが、
伊藤さんに確認した所、処理としては変わらないため、
スッキリして見えるLatestCombineでいいのではとの結論になったため
CombineLatestで統一しました。
Fixed 3e20404de39e4efef60b9d9c3e2f009f5dbaf47b

2023-09-08 02:29 UTC, sasuke9410 commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                .Subscribe(async _ => await groupManager.UpdateGroupsAsync())
意見が変わってすみません。
伊藤さんへ相談した所、非同期にしても特に問題ないとの結論に達したため、
非同期処理化しました。
Fixed b6e9bc888a7cc17ca3f8fa5d22a2697653f42849

2023-09-08 02:42 UTC, sasuke9410 commented on Assets/WebGLScripts.meta
Fixed 4483c9340b804d6a7d69c4873cf8751cca361b34

2023-09-08 02:47 UTC, sasuke9410 commented on Assets/WebGLTemplates/Holiday/index.js
Fixed 874fb5086302b67d97bc17f64ff579c2894342fe

2023-09-08 04:17 UTC, sasuke9410 commented on .gitignore
>  SecretVariables.cs*
Fixed 82ea200e0d7928fddda5bbeb7989bbfcaf8bdd42

2023-09-08 04:33 UTC, sasuke9410 commented on Assets/Holiday/Controls/TextChatControl/TextChatControlPresenter.cs
> +                .AddTo(stageDisposables);
Fixed 954879d94a4a20c8f3dc0029998bd71f6cc0bd10

2023-09-08 06:36 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +        private readonly Subject<Message> onMessageReceived = new Subject<Message>();
OnMessageSent/onMessageSent
　→ OnMessageSentは使用、onMessageSentは不使用
　→ 発火を受け取る(Subscribe)箇所はあるけど、発火(OnNext)する箇所が無い
OnNotificationReceived/onNotificationReceived
　→ onNotificationReceivedは使用、OnNotificationReceivedは不使用
　→ 発火している箇所はあるけど、発火を受け取る箇所はない
=> 発火/受け取りがセットになっていないため、コードカバレッジを通過させることが出来ない
と指摘を理解しました。

伊藤さんに確認した所、
「ステージ切り替え機能用に追加したが、現在使用していないため削除して問題ない」との話のため該当箇所を削除しました。
Fixed 7f7d42fecce395550251d9708bd5ad258cd14163

2023-09-12 02:09 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +            multiplayReady.Merge(textChatReady, voiceChatReady, spaceReady, p2PReady)
確認しました！

2023-09-12 02:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +                Logger.LogDebug($"Space, P2P, Multiplay, TextChat, VoiceChat, Space Ready: "
それでは違和感があると思います。
以下のようにしていただいても良いでしょうか？

`Space, P2P, Multiplay Ready`

2023-09-12 02:16 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +        private readonly Subject<Message> onMessageReceived = new Subject<Message>();
`MultiplayClient` クラスの `SendToEveryone` メソッドなども削除しませんか？
カバレッジ通っていないと思うのですが。

2023-09-12 02:25 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/TextChatControl/TextChatControlPresenter.cs
> +                .AddTo(stageDisposables);
確認しました。

2023-09-12 02:27 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                .Subscribe(async _ => await groupManager.UpdateGroupsAsync())
`await` も不要だと思います。
静的解析が警告を出していると思いますが。

2023-09-12 02:30 UTC, sus-taguchi-t commented on Assets/WebGLScripts.meta
`Assets/WebGLScripts~/node_modules.meta` は今後生成されることはないので `.gitignore` から削除してほしいです。

2023-09-12 02:31 UTC, sus-taguchi-t commented on Assets/WebGLTemplates/Holiday/index.js
確認しました。

2023-09-12 02:31 UTC, sus-taguchi-t commented on .gitignore
>  SecretVariables.cs*
確認しました。

2023-09-13 00:45 UTC, sasuke9410 commented on Assets/Holiday/App/AppState.cs
> +                Logger.LogDebug($"Space, P2P, Multiplay, TextChat, VoiceChat, Space Ready: "
Fixed 1411548d4084fd5483eb6ae02bcb259ff1d96aae

2023-09-13 00:54 UTC, sasuke9410 commented on Assets/WebGLScripts.meta
Fixed 01703d68c4107dcd8e170dd33ba71ab26d78bd4e

2023-09-15 08:56 UTC, mahaweilu commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                .Subscribe(async _ => await groupManager.UpdateGroupsAsync())
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/11/commits/e4a525fa82a5c50d613b4247aeb1c702699b3150

2023-09-15 08:56 UTC, mahaweilu commented on Assets/Holiday/App/AppState.cs
> +        private readonly Subject<Message> onMessageReceived = new Subject<Message>();
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/11/commits/e4a525fa82a5c50d613b4247aeb1c702699b3150

2023-09-15 09:13 UTC, mahaweilu commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +                .Subscribe(async _ => await groupManager.UpdateGroupsAsync())
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/11/commits/8e0e76d429bd6b3a000703892f8155509d8042c7

2023-09-15 09:15 UTC, mahaweilu approved these changes

2023-09-15 09:15 UTC, merged