Feature/switch different landscape
extreal-dev/Extreal.SampleApp.Holiday pull request #13
Opened 2023-09-18 01:09 UTC by mahaweilu

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装
- [ ] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました

## テスト
- [ ] 変更影響がある全てのテストが成功することを確認しました
- [ ] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響
- [ ] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-09-19 13:50 UTC, kiyohome requested changes

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/App/Config/LandscapeType.cs
> +        Hls = 3,
HlsとRealtimeは使ってますか？
使って無ければ削除しましょう。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/App/Config/MessageConfig.asset
> +    play Panorama, please re-enter the space.
前半の文で「Landscape playback」と書いているので、後半の文も「play Landscape」だとダメでしょうか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/App/Config/StageName.cs
> +
細かいですがこの空行はなくてもよくないでしょうか。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapeControlPresenter.cs
> +        protected override void Initialize
処理がない場合はオーバーライドしなくてもよくした記憶があるんですが、オーバーライド必要ですか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +        private async UniTask DoPlayAsync()
DoPlayAsyncメソッドはPlayメソッドのすぐ下にある方が分かりやすくないですか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +            this.panoramicRenderer = panoramicRenderer;
コンストラクタ引数の並び順と処理順を合わせた方がよくないでしょうか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +
この空行は不要ではないでしょうか。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +        private void ErrorReceived(string message)
イベントを購読するような処理であればErrorReceivedでいいですが、メソッドは通常動詞始まりがいいと思います。
HandleErrorでいかがでしょうか。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +                ErrorReceived(e.Message);
質問です。
UnityWebRequest.Result.Success以外の場合と例外が出る場合はそれぞれどのような時に発生しますか？
両方必要なのかな？と思いました。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/ILandscapePlayerFactory.cs
> +        UniTask<ILandscapePlayer> CreateAsync(StageName stageName);
CreateAsyncは同期メソッドにすればよくないでしょうか？
`ILandscapePlayer Create(StageName stageName);`
このインタフェースを実装したすべてのクラスが#pragma warning disable CS1998を付けて同期処理みたいです。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +            {
このカッコは必要ですか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
> +
空行が2行続いています。何か意図がありますか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
>          protected override void OnStageEntered(
メソッドの中身がない場合、オーバーライドは必要ですか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
>          protected override void OnStageExiting(
これもオーバーライド必要ですか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
> +        private void SwitchSpace(AppState appState, StageNavigator<StageName, SceneName> stageNavigator)
Spaceを増やすたびにここの実装が増えるような実装になってますね。
プルダウンを選択するとSpaceがAppStateに設定されているはずなので、AppStateに設定されたSpaceを使って処理するだけなので、個別のスペースやLandscapeTypeを意識した実装をしなくて良いはずです。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Controls/SpaceControl/SpaceControlView.cs
> +        [SerializeField] private TMP_Dropdown spaceDropdown;
ドロップダウンの見た目、違和感ないようにしてください。

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +            appState.SetSpace(assetHelper.SpaceConfig.Spaces.First());
ここでAppStateのSpaceを初期化しているとは、誰も思いつかず、メンテナンスしにくくないでしょうか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Spaces/VirtualSpace/VirtualSpacePresenter.cs
> +        private readonly AssetHelper assetHelper;
このクラスのフィールドは使ってますか？

2023-09-19 13:50 UTC, kiyohome commented on Assets/Holiday/Spaces/VirtualSpace/VirtualSpacePresenter.cs
> +
空行要りますか？

2023-09-19 13:50 UTC, kiyohome commented on .gitignore
> +WebGLBuild/PanoramicData/Panorama/
git cloneした人がREADMEの手順でプレイできますか？

2023-09-20 00:28 UTC, mahaweilu commented on Assets/Holiday/App/Config/LandscapeType.cs
> +        Hls = 3,
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/8fff9bfd734366308f628afdcac41dd992328086

2023-09-20 00:31 UTC, mahaweilu commented on Assets/Holiday/App/Config/MessageConfig.asset
> +    play Panorama, please re-enter the space.
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/bbbd5ce1ddefc1ac2fdb34c3dce93b4b73e80646

2023-09-20 00:33 UTC, mahaweilu commented on Assets/Holiday/App/Config/StageName.cs
> +
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/091d864261121c85204fbfaee642f08adbc4842b

2023-09-20 00:39 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapeControlPresenter.cs
> +        protected override void Initialize
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/bef592b3df67eaea1104ad1d4ad84e12f847ec01

2023-09-20 00:42 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +        private async UniTask DoPlayAsync()
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/e554ecc8d2ca8c0060e47a12b9f40683de3cec52

2023-09-20 00:48 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +            this.panoramicRenderer = panoramicRenderer;
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/a833f4c059b334ad4d3f1fc166fe68837ba5b0e8

2023-09-20 00:49 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/ae672d78cd8fc7bbd8d9db84dbd0a20646bcd041

2023-09-20 04:27 UTC, mahaweilu commented on Assets/Holiday/Controls/P2PControl/P2PControlPresenter.cs
> +            {
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/3104c163b6f0f7ba6f0aca2696baec97e7d5563e

2023-09-20 07:06 UTC, mahaweilu commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
> +
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/7daea02b1157c630deb11efb30debcedf06055fe

2023-09-20 07:09 UTC, mahaweilu commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
>          protected override void OnStageEntered(
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/19bfb0a4e921347b699feb8d100fd820e165fc10

2023-09-20 07:09 UTC, mahaweilu commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
>          protected override void OnStageExiting(
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/19bfb0a4e921347b699feb8d100fd820e165fc10

2023-09-21 01:48 UTC, mahaweilu commented on Assets/Holiday/Controls/SpaceControl/SpaceControlPresenter.cs
> +        private void SwitchSpace(AppState appState, StageNavigator<StageName, SceneName> stageNavigator)
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/86478d19abb09250728babc05e00008bfe5f06af

2023-09-21 02:20 UTC, mahaweilu commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +            appState.SetSpace(assetHelper.SpaceConfig.Spaces.First());
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/de50e93c8ec6eefe941293ac7a6ac66bd92b5e62

2023-09-28 01:20 UTC, mahaweilu commented on Assets/Holiday/Spaces/VirtualSpace/VirtualSpacePresenter.cs
> +        private readonly AssetHelper assetHelper;
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/cffda1514f4c8caecbafe89d268da75afd16fa63

2023-09-28 01:20 UTC, mahaweilu commented on Assets/Holiday/Spaces/VirtualSpace/VirtualSpacePresenter.cs
> +
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/cffda1514f4c8caecbafe89d268da75afd16fa63

2023-09-28 01:29 UTC, mahaweilu commented on .gitignore
> +WebGLBuild/PanoramicData/Panorama/
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/e27a0049d7698ab3587d458ef4cc101db64295b2

2023-09-28 01:36 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/ILandscapePlayerFactory.cs
> +        UniTask<ILandscapePlayer> CreateAsync(StageName stageName);
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/b5534b13f07e3162631a1b78fc51149c464559c3

2023-09-28 02:20 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +                ErrorReceived(e.Message);
>両方必要なのかな？
必要です。

>UnityWebRequest.Result.Success以外の場合と例外が出る場合はそれぞれどのような時に発生しますか？

if (request.result != UnityWebRequest.Result.Success)の場合
-例え場request.result = ConnectionErrorは「The server returned an error response. The request succeeded in communicating with the server, but received an error as defined by the connection protocol」指しているそうです。
- 参考：https://docs.unity3d.com/ja/2021.1/ScriptReference/Networking.UnityWebRequest.Result.html

UnityWebRequestTexture.GetTextureメソッド自体が例外をスローすることがあります。
- 不正な形式のURL
- 存在しないドメインや解決できないホスト名を指定した場合

2023-09-28 02:22 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +        private void ErrorReceived(string message)
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/427e475e6ff8e07a46be6bae69d1a26557de1e15

2023-09-28 06:22 UTC, mahaweilu commented on Assets/Holiday/Controls/SpaceControl/SpaceControlView.cs
> +        [SerializeField] private TMP_Dropdown spaceDropdown;
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/5c682b9708780922cf3ffbe59f49ca9297e8a602

2023-09-28 07:39 UTC, mahaweilu commented on .gitignore
> +WebGLBuild/PanoramicData/Panorama/
子の指摘に関係ないのですが、
追加で細かい修正（命名変更など）をしましたのでご確認お願い致します。

https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/91a81caf3c36a47f3a7f1766a7da6bf7080c27eb

https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/94dd2ec32f5622cf4f8be4dc665623da537bef95

2023-09-29 05:29 UTC, mahaweilu commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +                ErrorReceived(e.Message);
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/d88f914fd2a3b48226647854e96deb576ac12d6a

2023-09-29 08:27 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +                ErrorReceived(e.Message);
必要ないと判断した理由を教えてください。

2023-09-29 09:08 UTC, kiyohome commented on Assets/Holiday/Controls/LandscapeControl/LandscapePlayers/Image/LandscapeImagePlayer.cs
> +                ErrorReceived(e.Message);
張さん＞
理由：以下の操作で
・[UnityWebRequest.Result.DataProcessingError](https://docs.unity3d.com/ja/2021.1/ScriptReference/Networking.UnityWebRequest.Result.DataProcessingError.html)と[ConnectionError](https://docs.unity3d.com/ja/2021.1/ScriptReference/Networking.UnityWebRequest.Result.ConnectionError.html)、
[ProtocolError](https://docs.unity3d.com/ja/2021.1/ScriptReference/Networking.UnityWebRequest.Result.ProtocolError.html)発生させ、catchロジックでcatchできたので、catchロジックですべてcatchできると思いました。
・配信する画像ファイルtxtで開いて適当の文字を入れて保存する
・ネットワーク断線
・存在しないドメインを指定（[https:nonexistent-domain.com](https://app.slack.com/client/nonexistent-domain.com)

伊藤＞
URLのファイルが存在しない場合（404）も例外ですか？

張さん＞
> URLのファイルが存在しない場合も例外
はい、そうです。
> 404
ただ404ではなく、403エラーのです。
例えば「https://extreal-webgl.s3.ap-northeast-1.amazonaws.com/Panoramic/PanoramicImageStage11.jpg」

2023-09-29 09:10 UTC, kiyohome commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +            appState.SetSpace(assetHelper.SpaceConfig.Spaces.First());
GroupSelectionScreenの中で初期化しているとは、誰も思いつかないのでは？という質問です。

2023-09-29 09:12 UTC, kiyohome commented on Assets/Holiday/Spaces/VirtualSpace/VirtualSpacePresenter.cs
> +        private readonly AssetHelper assetHelper;
Loggerも使ってないように見えたんですが、使ってますか？

2023-09-29 09:15 UTC, mahaweilu commented on Assets/Holiday/Spaces/VirtualSpace/VirtualSpacePresenter.cs
> +        private readonly AssetHelper assetHelper;
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/4109c12f8a842d3811db9e004074c0206920f48d

2023-09-29 09:20 UTC, kiyohome commented on .gitignore
> +WebGLBuild/PanoramicData/Panorama/
360度画像と360度動画はリポジトリに含めてない気がするんですが、下記のREADMEを見てプレイして空間切り替えは動きますか？
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/blob/feature/switch-different-landscape/README.md

2023-09-29 09:21 UTC, kiyohome requested changes

2023-09-29 09:21 UTC, kiyohome commented on WebGLBuild/README.md
> +1. Put panoramic image/video files in the `WebGLBuild/PanoramicData/Panorama/` directory.
上のコマンドをたたく手順が最後の方がよくないですか？

2023-09-29 09:21 UTC, kiyohome commented on WebGLBuild/README.md
> +1. Put panoramic image/video files in the `WebGLBuild/PanoramicData/Panorama/` directory.
ファイル名は何でもいいですか？

2023-09-29 09:39 UTC, mahaweilu commented on WebGLBuild/README.md
> +1. Put panoramic image/video files in the `WebGLBuild/PanoramicData/Panorama/` directory.
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/b5525b2489d12040712dafa4fcce5cf7057fcea8

2023-09-29 09:39 UTC, mahaweilu commented on WebGLBuild/README.md
> +1. Put panoramic image/video files in the `WebGLBuild/PanoramicData/Panorama/` directory.
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/b5525b2489d12040712dafa4fcce5cf7057fcea8

2023-09-29 09:49 UTC, mahaweilu commented on .gitignore
> +WebGLBuild/PanoramicData/Panorama/
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/21b6a000a243583352fc11fa812acfe4ab99c31d

2023-09-29 10:11 UTC, mahaweilu commented on Assets/Holiday/Screens/GroupSelectionScreen/GroupSelectionScreenPresenter.cs
> +            appState.SetSpace(assetHelper.SpaceConfig.Spaces.First());
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/3aae01952a3b2acb87dff62f093e3382f1f69032

https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/97e4d0d41c37e71d97fa2da0b633ff1aed176b59

2023-10-03 01:59 UTC, mahaweilu commented on .gitignore
> +WebGLBuild/PanoramicData/Panorama/
fixed https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/13/commits/5de629925f6571c3141add276dff2974f46be456

2023-10-04 07:02 UTC, kiyohome approved these changes

2023-10-04 07:02 UTC, merged