安全にDisposeできるようにDisposeパターンを適用する
extreal-dev/Extreal.SampleApp.Holiday pull request #2
Opened 2023-01-24 06:19 UTC by kiyohome

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装
- [ ] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました

## テスト
- [ ] 変更影響がある全てのテストが成功することを確認しました
- [ ] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響
- [ ] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-01-24 07:05 UTC, sus-taguchi-t requested changes

2023-01-24 07:05 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppState.cs
> +    public class AppState : DisposableBase
これでは結局 Dispose のために継承するクラスを消費してしまうので不便なままではないでしょうか。
私は Dispose したい各クラスの中で SafeDisposer クラスのインスタンスを作成してそれを使用するような形を想定していましたがいかがでしょう。

2023-01-24 08:37 UTC, kiyohome commented on Assets/Holiday/App/AppState.cs
> +    public class AppState : DisposableBase
どちらを使ってもいいです。
継承使えるとこはファイナライザなど強制するスコープが広いので継承を使っておいて、継承を外したくなったらロジッククラスを使う想定です。
ガイドには２つの方法を記載する予定です。

2023-01-30 06:11 UTC, sus-taguchi-t requested changes

2023-01-30 06:11 UTC, sus-taguchi-t commented on Assets/Holiday.MultiplayServer/MultiplayServer.cs
>          private readonly CompositeDisposable disposables = new CompositeDisposable();
抑制する同じ解析が 2 つ以上ある場合、`System.Diagnostics.CodeAnalysis.SuppressMessage` 属性を各フィールドに付けるより `#pragma` で囲った方が見やすくて良いと思いました。
それとも明確にそれぞれに対して解析を抑制していることが分かりやすくなるようにこの措置をしているのでしょうか？

_cf._
```csharp
#pragma warning disable CC0033
        private readonly CancellationTokenSource cts = new CancellationTokenSource();

        private readonly CompositeDisposable disposables = new CompositeDisposable();
#pragma warning restore CC0033
```

他のクラスについても同様です。

2023-01-30 06:11 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/Common/ChatChannelBase.cs
> +        [SuppressMessage("Usage", "CC0033")] private readonly Subject<Unit> onConnectFailed = new Subject<Unit>();
属性の後に改行していないのは何か意図がありますでしょうか？

2023-01-30 07:54 UTC, kiyohome commented on Assets/Holiday.MultiplayServer/MultiplayServer.cs
>          private readonly CompositeDisposable disposables = new CompositeDisposable();
好みの問題かもですが、1つずつ判断して付けていく方が安全だと思います。

あと#pragmaや#ifは、個人的にはソースのインデントが見にくいので、できるだけ使いたくないと思ってます。
慣れてないだけかもですが個人的には可読性がとても落ちて読みづらいな、と思ってます。
インデントを合わせればいいだけかもですが。

#ifとかも同じでできれば使いたくない、使う場合は局所化したい、と考えています。

2023-01-30 08:08 UTC, kiyohome commented on Assets/Holiday/Controls/Common/ChatChannelBase.cs
> +        [SuppressMessage("Usage", "CC0033")] private readonly Subject<Unit> onConnectFailed = new Subject<Unit>();
意図ないので他に合わせて改行するように修正しました！
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/2/commits/dcec5b92c3f1a44c57e9f7b1dcd48a726876e357
クラス内でしか使ってないメソッドをprivateに変更も入ってしまいました。
コミット単位がダサくてすみません。

2023-01-30 08:13 UTC, sus-taguchi-t commented on Assets/Holiday.MultiplayServer/MultiplayServer.cs
>          private readonly CompositeDisposable disposables = new CompositeDisposable();
分かりました。
確かに適用する物の直前にあった方が万人が見て分かりやすいので良いと思います。

2023-01-30 08:14 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/Common/ChatChannelBase.cs
> +        [SuppressMessage("Usage", "CC0033")] private readonly Subject<Unit> onConnectFailed = new Subject<Unit>();
確認しました！
コミット単位は大丈夫です！！

2023-01-30 08:18 UTC, sus-taguchi-t approved these changes

2023-01-30 08:18 UTC, merged