大規模マルチプレイおよびテキストチャットを導入
extreal-dev/Extreal.SampleApp.Holiday pull request #23
Opened 2023-12-27 02:31 UTC by sus-taguchi-t

# 何の変更を加えましたか？

- 以下の仕様に変更しました
  - スペースごとにメッセージングを用いた大規模マルチプレイ
  - グループごとにチャット
    - ボイスチャットは P2P のまま
    - テキストチャットは Messaging に変更

# 何を確認しましたか?

## 実装
- [x] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました

## テスト
- [x] 変更影響がある全てのテストが成功することを確認しました
- [ ] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響

https://github.com/extreal-dev/Extreal.Guide/pull/56

- [x] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-12-27 06:25 UTC, mahaweilu commented on Assets/Plugins/ParrelSync/ScriptableObjects/ParrelSyncProjectSettings.asset
質問です。ParrelSyncに関する変更は何のための変更ですか？

2023-12-27 06:25 UTC, mahaweilu commented on Assets/WebGLScripts~/package.json
> +    "@extreal-dev/extreal.integration.messaging.redis": "../../Packages/Extreal.Integration.Messaging.Redis/WebScripts~/",
リマインド：ライブラリ対応完了後、こちらの反映もお願いします。

2023-12-27 06:25 UTC, mahaweilu commented on Assets/WebGLScripts~/rollup.config.ts
> +            dedupe: ["@extreal-dev/extreal.integration.web.common"],
package.jsonでmessaging.redisのパッケージをnpmから参照するようになってから、こちらいらなくなりますね？

2023-12-27 06:25 UTC, mahaweilu commented on Packages/manifest.json
リマインド：ライブラリ対応後、こちらの反映（git urlから取得するように）もお願いします。

2023-12-27 06:25 UTC, mahaweilu commented on Assets/Holiday.PerformanceTest/Extreal.SampleApp.Holiday.PerformanceTest.asmdef
> +        "Extreal.Integration.Multiplay.Common"
Extreal.Integration.Multiplay.Messagingになるんですね？リポジトリ名修正後、対応お願いします。

2023-12-27 06:25 UTC, mahaweilu commented on Assets/Holiday/Controls/TextChatControl/TextChatRoom.cs
> +                await messagingClient.CreateGroupAsync(groupConfig);
>ネットワーク切断時はユーザーに通知する。

↑の非機能要件によってここではメッセージングサーバにアクセスできない場合の例外処理が必要です。試したことろ、TimeoutExceptionでローディング画面から開けなかったです。

2023-12-28 06:40 UTC, sus-yoshikane-t requested changes

2023-12-28 06:40 UTC, sus-yoshikane-t commented on Assets/WebGLScripts~/yarn.lock
> +    "@extreal-dev/extreal.integration.web.common" "^1.0.0"
NGOのものが残っています。(消し方分かりませんが)

2023-12-28 06:40 UTC, sus-yoshikane-t commented on ProjectSettings/PackageManagerSettings.asset
> +    - io.livekit
今回は不要だと思います。

2024-01-09 06:07 UTC, mahaweilu commented on Assets/Plugins/ParrelSync/ScriptableObjects/ParrelSyncProjectSettings.asset
以下が理由でした。Reimport Allで確認し、特に問題なかったため、対応不要とします
Unity Editorを開くたびに変更が発生するためプッシュした

2024-01-09 08:20 UTC, mahaweilu commented on Assets/WebGLScripts~/yarn.lock
> +    "@extreal-dev/extreal.integration.web.common" "^1.0.0"
関連するところ含めて削除しました。
[3898611](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/3898611ba8155e913c6b5364e2784c68b196cd93)

2024-01-09 08:21 UTC, mahaweilu commented on ProjectSettings/PackageManagerSettings.asset
> +    - io.livekit
対応しました。ビルド設定で不要のところもついでに削除しました。
[e3948f1](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/e3948f1fe6b235b3a0854d76d6ab5eb55dad50e5)

2024-01-09 08:37 UTC, mahaweilu commented on Assets/Holiday/Controls/TextChatControl/TextChatRoom.cs
> +                await messagingClient.CreateGroupAsync(groupConfig);
以下で対応しました。
[580c985](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/580c985a6b1891e677a8ad8f83ed5a93f25a044d)

[7f16ac0](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/7f16ac01508af403747618c9d9190bc0cd0e75d6)

2024-01-09 08:38 UTC, mahaweilu commented on Assets/Holiday.PerformanceTest/Extreal.SampleApp.Holiday.PerformanceTest.asmdef
> +        "Extreal.Integration.Multiplay.Common"
以下で対応しました。
[580c985](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/580c985a6b1891e677a8ad8f83ed5a93f25a044d)

2024-01-10 01:02 UTC, sus-yoshikane-t commented on Assets/WebGLScripts~/yarn.lock
> +    "@extreal-dev/extreal.integration.web.common" "^1.0.0"
確認しました。

2024-01-10 01:03 UTC, sus-yoshikane-t commented on ProjectSettings/PackageManagerSettings.asset
> +    - io.livekit
確認しました。

2024-01-16 11:25 UTC, kiyohome requested changes

2024-01-16 11:25 UTC, kiyohome commented on Assets/Holiday/App/Config/MessagingConfig.cs
> +namespace Extreal.SampleApp.Holiday
App.Configを入れてませんか？

2024-01-16 11:25 UTC, kiyohome commented on Assets/Holiday/Controls/ClientControl/ClientControlScope.cs
> +            builder.RegisterComponent(queuingMessagingClient);
queuingMessagingClientをRegisterしてるのはなぜですか？

2024-01-16 11:25 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +namespace Extreal.SampleApp.Holiday.Controls.MassivelyMultiplyControl.Client
MassivelyMultiplyControl？

2024-01-16 11:25 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            var groups = await messagingClient.ListGroupsAsync();
分けてやってみてという話しでしたが、サンプル見るとmultiplayClientに寄せたいですね。

2024-01-17 07:48 UTC, mahaweilu commented on Assets/Holiday/Controls/ClientControl/ClientControlScope.cs
> +            builder.RegisterComponent(queuingMessagingClient);
memo: group管理で使っているため

2024-01-17 07:52 UTC, mahaweilu commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            var groups = await messagingClient.ListGroupsAsync();
memo: Multiplay.MessagingのMultiplayClient.csにListGroupAsync()などグループ管理系のメソッドを追加

2024-01-18 01:51 UTC, sus-yoshikane-t approved these changes

2024-01-18 05:46 UTC, mahaweilu commented on Assets/Holiday/App/Config/MessagingConfig.cs
> +namespace Extreal.SampleApp.Holiday
App.Configの命名空間に入れて対応します。

2024-01-18 05:49 UTC, mahaweilu commented on Assets/Holiday/Controls/ClientControl/ClientControlScope.cs
> +            builder.RegisterComponent(queuingMessagingClient);
グループ管理はMessagingClientが行っているためです。
MultiplayClient.csにもグループ管理を入れて対応します。その場合こちらのRegisterが要らなくなります。

2024-01-18 05:49 UTC, mahaweilu commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +namespace Extreal.SampleApp.Holiday.Controls.MassivelyMultiplyControl.Client
typoを修正します。

2024-01-18 05:49 UTC, mahaweilu commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            var groups = await messagingClient.ListGroupsAsync();
MultiplayClient.csにもグループ管理を入れて対応します。

2024-01-23 10:41 UTC, mahaweilu commented on Assets/Holiday/App/Config/MessagingConfig.cs
> +namespace Extreal.SampleApp.Holiday
修正しました。
[c8fdbe4](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/c8fdbe46607680913f0937ffbd30c496336129f0)

2024-01-23 10:42 UTC, mahaweilu commented on Assets/Holiday/Controls/ClientControl/ClientControlScope.cs
> +            builder.RegisterComponent(queuingMessagingClient);
以下で対応しました。
[edb6481](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/edb6481dae47034ed37c4d31d82ce859a8e5a3e9)

2024-01-23 10:44 UTC, mahaweilu commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +namespace Extreal.SampleApp.Holiday.Controls.MassivelyMultiplyControl.Client
対応しました。以下MultiplayControlディレクトリの配下ファイルから確認お願いします。
[edb6481](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/edb6481dae47034ed37c4d31d82ce859a8e5a3e9)

2024-01-23 10:46 UTC, mahaweilu commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            var groups = await messagingClient.ListGroupsAsync();
MultiplayClient.csにグループ一覧取得メソッドを入れて対応しました。
[edb6481](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/edb6481dae47034ed37c4d31d82ce859a8e5a3e9)

2024-01-31 10:33 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +namespace Extreal.SampleApp.Holiday.Controls.MassivelyMultiplyControl.Client
ディレクトリ構成に合わせて名前空間を修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/bb8910c0a7bbb01fcee48c717679a2da9c47f6dd

2024-01-31 10:38 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/Common/Multiplay/HolidayPlayerInputValues.cs
JsonConvert を使用するため、そちらの方式に合わせてコードを修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/2c636482d99dcf9e14a6e024ddb5c3d9698ecbc8

2024-01-31 10:38 UTC, sus-taguchi-t commented on Assets/Holiday/App/Config/MultiplayConfig.cs
マルチプレイとテキストチャットでそれぞれ接続先情報を設定できるように修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/bd35484414f443e6caf83ec39b40e274e1d97944

2024-02-02 09:10 UTC, kiyohome approved these changes

2024-02-05 06:37 UTC, sus-taguchi-t commented on Assets/WebGLScripts~/package.json
> +    "@extreal-dev/extreal.integration.messaging.redis": "../../Packages/Extreal.Integration.Messaging.Redis/WebScripts~/",
対応しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/6900df86f405e7e52e7ec8f99139f8eac6b99f08

2024-02-05 06:38 UTC, sus-taguchi-t commented on Assets/WebGLScripts~/rollup.config.ts
> +            dedupe: ["@extreal-dev/extreal.integration.web.common"],
対応しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/6900df86f405e7e52e7ec8f99139f8eac6b99f08

2024-02-05 06:38 UTC, sus-taguchi-t commented on Packages/manifest.json
対応しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/23/commits/6900df86f405e7e52e7ec8f99139f8eac6b99f08

2024-02-05 06:39 UTC, merged