テキストチャットをスペースごとにできるようにする
extreal-dev/Extreal.SampleApp.Holiday pull request #30
Opened 2024-04-03 09:09 UTC by sus-taguchi-t

# 何の変更を加えましたか？

- テキストチャットをスペースごとにできるようにしました
- everyone message を P2P のテキストチャットを使用するように変更しました

# 何を確認しましたか?

## 実装
- [x] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました

## テスト
- [x] 変更影響がある全てのテストが成功することを確認しました
- [x] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響
- [x] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2024-04-03 09:32 UTC, kiyohome requested changes

2024-04-03 09:32 UTC, kiyohome commented on Assets/Holiday/Controls/GroupControl/GroupControlPresenter.cs
> +            textChatClient.OnMessageReceived
P2PのTextChatClientへの依存をGroupManagerに隠蔽できないですかね？
ここまで出てくるとTextChatControlと勘違いしそうだったので、何とかできないかなと思いました。

2024-04-04 00:06 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/GroupControl/GroupControlPresenter.cs
> +            textChatClient.OnMessageReceived
できると思います。
確かに GroupManager クラスの責務にも反さないので良いと思います。

2024-04-04 01:26 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/GroupControl/GroupControlPresenter.cs
> +            textChatClient.OnMessageReceived
修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/30/commits/241bfa416da31172c6ad59beb52561e2162ed3cc

2024-04-04 01:42 UTC, kiyohome commented on Assets/Holiday/Controls/GroupControl/GroupControlPresenter.cs
> +            textChatClient.OnMessageReceived
いいですねーすっきりしましたね！

2024-04-04 01:43 UTC, kiyohome approved these changes

2024-04-04 06:14 UTC, sus-yoshikane-t approved these changes

2024-04-04 06:15 UTC, merged