Introduce Addressables and customize to encrypt/decrypt the AssetBundles
extreal-dev/Extreal.SampleApp.Holiday pull request #4
Opened 2023-02-23 04:15 UTC by kiyohome

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装
- [ ] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました

## テスト
- [ ] 変更影響がある全てのテストが成功することを確認しました
- [ ] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響
- [ ] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-03-06 07:13 UTC, sus-taguchi-t requested changes

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +        m_Value: https://extreal-public.s3.ap-northeast-1.amazonaws.com/[AddressablesVariables.AppVersion]
サーバーの URL を載せたままで大丈夫でしょうか？
ここを `[SecretVariables.ServerAddress]/[AddressablesVariables.AppVersion]` とすれば隠すことができます。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +            disposable.Dispose();
`using var disposable = await assetProvider.LoadAsset<TAsset>();` として `disposable.Dispose();` を削除して良いと思います。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +                nextFunc?.Invoke();
ここは `await` するか `Forget()` した方が良いです。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +#pragma warning restore CS1998
`stageNavigator.ReplaceAsync(nextStage).Forget();` を `await stageNavigator.ReplaceAsync(nextStage);` に変更すればプラグマを外せます。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        protected override void ReleaseManagedResources() => onDownloaded.Dispose();
`onDownloading` が `Dispose()` されていません。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        private readonly Subject<DownloadStatus> onDownloaded = new Subject<DownloadStatus>();
複数のアセットを同時にダウンロードしないことを想定しているという認識であっていますでしょうか？

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetProvider.cs
> +            nextFunc?.Invoke();
ここは `await` するか `Forget()` した方が良いです。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +                })
```csharp
.Where(ready => ready)
.Subscribe(_ => multiplayRoom.JoinAsync().Forget())
```
の方がすっきりして良いと思います。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +                ngoClient, assetHelper.NgoConfig, assetHelper, appState.Avatar.Value.AssetName);
`assetHelper.NgoConfig` は流さなくても良いと思います。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            => NetworkManager.Singleton.SpawnManager.SpawnedObjects;
プロパティもクラスの頭にまとめた方が読みやすいです。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            foreach (var existingObject in SpawnedObjects.Values)
同フレーム内にこのユーザと他のユーザが立て続けにスポーンした場合にここの `foreach` がエラーを吐いて落ちる気がします。
`var spawnedObjects = SpawnedObjects.Values.ToArray();` 等でコレクションを保存してから `foreach` を回した方が良いと思います。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/ConfirmationScreen/ConfirmationScreenPresenter.cs
> +    }
**リファクタリング事項（今回のスコープ外）**
ベースクラスでこれらのメソッドを `protected virtual` で何も処理をしない形で宣言しておけば継承先でこれらのようにオーバーライドしないで済むと思いました。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +        public void ToggleVisibility(bool isVisible)
`SetVisibility` の方がしっくりきます。

2023-03-06 07:13 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +                                     $"( {downloaded.Item1}{downloaded.Item2} / {total.Item1}{total.Item2} )";
両端の空白は必要でしょうか？

2023-03-06 07:21 UTC, sus-taguchi-t requested changes

2023-03-06 07:21 UTC, sus-taguchi-t commented on Assets/Holiday.MultiplayCommon/Avatars/AvatarProvider.cs
> +}
アバターはクライアント側でのみ使用するようになったので `Holiday.MultiplayCommon` ではなく `Holiday` に移した方が良いと思います。

2023-03-06 07:21 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +            ClearAssetBundleCacheOnDev();
`#if !HOLIDAY_PROD` のプリプロセッサはこちらに書いた方が本番環境時に関数呼び出しのオーバーヘッドが減少して良いと思います。

2023-03-06 13:40 UTC, kiyohome commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +        m_Value: https://extreal-public.s3.ap-northeast-1.amazonaws.com/[AddressablesVariables.AppVersion]
[SecretVariables.ServerAddress]とは何ですか？
単純に消すのではダメですか？

2023-03-06 13:44 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetHelper.cs
> +            disposable.Dispose();
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/6345801edb02c60231c61b263a10716c7a2fc265

2023-03-06 13:57 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetHelper.cs
> +                nextFunc?.Invoke();
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/048afea0bd2eb649ae415c8fbe8d6ded01b68a78

2023-03-06 13:57 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetHelper.cs
> +                nextFunc?.Invoke();
単純に質問です。
なんでawait or forget した方がいいんですか？

2023-03-06 14:01 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetHelper.cs
> +#pragma warning restore CS1998
待つ必要がないのにawaitを付けるのは変なので、プラグマ付けたままでよくないでしょうか？

2023-03-06 14:03 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        protected override void ReleaseManagedResources() => onDownloaded.Dispose();
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/e8070bd7072b2177d9398daea0158d2b432297b2

2023-03-06 14:08 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        private readonly Subject<DownloadStatus> onDownloaded = new Subject<DownloadStatus>();
どういう使われ方を想定していますか？

2023-03-06 14:12 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetProvider.cs
> +            nextFunc?.Invoke();
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/54899405aeb2c795819e5b2565eb22bccb10f6f2

2023-03-06 14:16 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +                })
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/f50440480e5724ac360ece631f4e03008bac0437

2023-03-06 14:20 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +                ngoClient, assetHelper.NgoConfig, assetHelper, appState.Avatar.Value.AssetName);
assetHelperから取れるから、ここで渡さなくてもいいということですかね？
NgoConfigに依存していることが分かるので、ここで渡していてもいいと思いますが、何か懸念がありますか？

2023-03-06 14:23 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            => NetworkManager.Singleton.SpawnManager.SpawnedObjects;
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/ad6dee02ad31b4664214718344e9653b9fe74103

2023-03-06 14:36 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            foreach (var existingObject in SpawnedObjects.Values)
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/b0f3ea84c01ef3f8dd7d39fac5560353d71b5d0f

2023-03-06 14:37 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            foreach (var existingObject in SpawnedObjects.Values)
ToArrayだと落ちないんですかね？

2023-03-06 14:39 UTC, kiyohome commented on Assets/Holiday/Screens/ConfirmationScreen/ConfirmationScreenPresenter.cs
> +    }
Presenterを実装する人は3つのタイミングを意識して欲しいので、今のままでいいと思いますが、いかがでしょうか。

2023-03-06 14:40 UTC, kiyohome commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +        public void ToggleVisibility(bool isVisible)
Setterは情報量が少なくてあまり好きでないので、今のままでもいいかと思いますが、いかがでしょうか。

2023-03-06 14:47 UTC, kiyohome commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +                                     $"( {downloaded.Item1}{downloaded.Item2} / {total.Item1}{total.Item2} )";
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/2e03d840d783ee4f90b35755fa825e260482b6bc

2023-03-06 15:05 UTC, kiyohome commented on Assets/Holiday.MultiplayCommon/Avatars/AvatarProvider.cs
> +}
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/44c739f73b4dc33677b5ebb863ce51465bc06bc1

2023-03-06 15:07 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +            ClearAssetBundleCacheOnDev();
InitializeAppの中を見やすくするのと、性能劣化のトレードオフになるかと思います。
アプリ起動時に一度だけしか呼ばれないので、今のままでいいと思いますがいかがでしょうか。

2023-03-07 00:51 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +                nextFunc?.Invoke();
それらをしないで UniTask を呼ぶとタスクがリークするという記事がありました。
https://bravememo.hatenablog.com/entry/2022/09/05/113701

2023-03-07 00:52 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +#pragma warning restore CS1998
確かにそのままで良いと思いました。

2023-03-07 00:54 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        private readonly Subject<DownloadStatus> onDownloaded = new Subject<DownloadStatus>();
複数の `DownloadAsync` を `Forget()` で同時に呼び出すことがないという想定です。

2023-03-07 00:55 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +                ngoClient, assetHelper.NgoConfig, assetHelper, appState.Avatar.Value.AssetName);
そうです。

 > NgoConfigに依存していることが分かるので

そういう意味合いがあるのであればこのままでよいと思います！
特に懸念はないです、

2023-03-07 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            foreach (var existingObject in SpawnedObjects.Values)
`ToArray` だと `SpawnedObjects` にオブジェクトが追加/削除されてもローカルで保持しているコレクションの増減はないので foreach が落ちなくなります。

ただ一方で `SpawnedObjects` からオブジェクトが削除 されると `foreach` の途中で `existingObject` に `null` が入る可能性があるのでそのチェックが必要になることに今気づきました。

2023-03-07 02:10 UTC, kiyohome commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +        public void ToggleVisibility(bool isVisible)
SwitchVisibilityにします。

2023-03-07 02:19 UTC, sus-taguchi-t commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +        m_Value: https://extreal-public.s3.ap-northeast-1.amazonaws.com/[AddressablesVariables.AppVersion]
> [SecretVariables.ServerAddress]とは何ですか？

Addressables は設定値をビルド時やプレイヤーの実行時に評価させる手法を提供しています。
角括弧でくくるとビルド時評価になります。
`SecretVariables` クラスの静的なフィールド `ServerAddress` を用意することでこの値がビルド時に評価されて設定値に代入されます。


> 単純に消すのではダメですか？

単純に消しても解決はしますが、push する度に手動で消すにはリスクがあると思います。
ビルド時評価にしておけばスクリプトベースで取得できる状態となるので、あとはこのスクリプトを `.gitignore` に入れるだけでサーバの接続情報が push されないようになります。
またスクリプト `SecretVariables.cs` は既に `.gitignore` に入っています。

2023-03-07 02:25 UTC, kiyohome commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +        public void ToggleVisibility(bool isVisible)
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/c0dfd25c39f11bbd9ae92ba59f8087a52647e03a

2023-03-07 02:26 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +                nextFunc?.Invoke();
PBI を上げました。

2023-03-07 02:27 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            foreach (var existingObject in SpawnedObjects.Values)
ただ一方で `SpawnedObjects` からオブジェクトが削除 されると `foreach` の途中で `existingObject` に `null` が入る可能性があるのでそのチェックが必要になることに今気づきました。

2023-03-07 02:28 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/ConfirmationScreen/ConfirmationScreenPresenter.cs
> +    }
そのような意図があるのであればこのままで良いと思います！

2023-03-07 02:29 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +            ClearAssetBundleCacheOnDev();
確かにその通りです。
このままで良いと思います！

2023-03-07 02:29 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +            disposable.Dispose();
確認しました！

2023-03-07 02:30 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetHelper.cs
> +                nextFunc?.Invoke();
確認しました！

2023-03-07 02:32 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        protected override void ReleaseManagedResources() => onDownloaded.Dispose();
確認しました！

2023-03-07 02:33 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetProvider.cs
> +            nextFunc?.Invoke();
確認しました！

2023-03-07 02:33 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayControlPresenter.cs
> +                })
確認しました！

2023-03-07 02:34 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            => NetworkManager.Singleton.SpawnManager.SpawnedObjects;
確認しました！

2023-03-07 02:36 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +        public void ToggleVisibility(bool isVisible)
確認しました！

2023-03-07 02:37 UTC, sus-taguchi-t commented on Assets/Holiday/Screens/LoadingScreen/LoadingScreenView.cs
> +                                     $"( {downloaded.Item1}{downloaded.Item2} / {total.Item1}{total.Item2} )";
確認しました！

2023-03-07 02:41 UTC, sus-taguchi-t commented on Assets/Holiday.MultiplayCommon/Avatars/AvatarProvider.cs
> +}
確認しました！

2023-03-07 03:06 UTC, kiyohome commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +        m_Value: https://extreal-public.s3.ap-northeast-1.amazonaws.com/[AddressablesVariables.AppVersion]
Fixed!
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/4/commits/680f6d31f4b08cc708a21d35fe49c9281aab97dd

2023-03-07 03:12 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        private readonly Subject<DownloadStatus> onDownloaded = new Subject<DownloadStatus>();
アプリの要件や設計として、複数同時に呼び出すケースはありそうですかね？

2023-03-07 03:18 UTC, kiyohome commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            foreach (var existingObject in SpawnedObjects.Values)
ToArrayした後にnullが入るんですか？
ToArrayしてない場合の話しではないですよね？

2023-03-07 03:32 UTC, sus-taguchi-t commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        private readonly Subject<DownloadStatus> onDownloaded = new Subject<DownloadStatus>();
複数同時に呼び出した方が早く処理が終わるので、速度重視の場合は複数同時に呼び出すケースもあるかなと思います。

2023-03-07 04:22 UTC, sus-taguchi-t commented on Assets/Holiday/Controls/MultiplayControl/MultiplayRoom.cs
> +            foreach (var existingObject in SpawnedObjects.Values)
私の勘違いで、`existingObject` に `null` が入ることはなかったです。
このままで大丈夫です！

2023-03-07 04:26 UTC, sus-taguchi-t commented on Assets/AddressableAssetsData/AddressableAssetSettings.asset
> +        m_Value: https://extreal-public.s3.ap-northeast-1.amazonaws.com/[AddressablesVariables.AppVersion]
確認しました！

2023-03-07 04:45 UTC, kiyohome commented on Assets/Holiday/App/Common/AssetProvider.cs
> +        private readonly Subject<DownloadStatus> onDownloaded = new Subject<DownloadStatus>();
アセット名をイベント通知に含める対応をモジュールの取り込み時に入れることにしましょう。
Holidayはモジュール取り込み時に自動で適用されるので、ここでは修正しないで進めましょう。

2023-03-07 04:47 UTC, sus-taguchi-t approved these changes

2023-03-07 04:48 UTC, merged