アプリケーションの利用状況可視化をできるようにする
extreal-dev/Extreal.SampleApp.Holiday pull request #8
Opened 2023-05-30 12:46 UTC by kiyohome

# 何の変更を加えましたか？

- データ可視化基盤としてGrafana/LokiのDocker Composeファイル、ダッシュボードの定義ファイルを作成しました。
- HolidayアプリにLokiにログデータを送る実装を追加しました。Commonに追加したHookを使っています。
- 直接関係ないですがAssetWorkflowの設定でHostingをOffに変更しました。

# 何を確認しましたか?

## 実装
- [x] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました

## テスト
- [x] 変更影響がある全てのテストが成功することを確認しました
  - アプリ利用状況可視化を無効化した場合にエラーが出ず機能を使えることを確認済み
  - アプリ利用状況可視化を有効化した場合にログ収集とダッシュボード反映を確認済み
    - エラーログの出力が無かったので追加済み
  - アプリ利用状況可視化を有効化かつLokiにアクセスできない場合にエラーが出ず機能を使えることを確認済み
- [x] 変更影響があるソースのテストカバレッジが100%になることを確認しました
  - 上記テストの無効化した場合とLokiにアクセスできない場合の処理を除いてカバレッジ確認済み
  - カバレッジ未達は上記テストのパスと査読で問題ないと判断しました。

## 変更影響
- [x] GuideのSample Applicationに変更が反映されることを確認しました
  - https://github.com/extreal-dev/Extreal.Guide/pull/46

# レビュアーへのメッセージ

- https://github.com/extreal-dev/Extreal.Guide/pull/46 を先にレビューしながら、このPRもレビューしてもらうと分かりやすいと思います。

2023-06-12 06:13 UTC, sus-taguchi-t requested changes
私の環境でのみ警告を発しているであろう静的解析の対応をしました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/3078690a5137d5bcecde3a44cc6441911df6f314

2023-06-12 06:13 UTC, sus-taguchi-t commented on .editorconfig
> +# dotnet_naming_style.disallowed_style.required_suffix = ____RULE_VIOLATION____
カプセル化しない記述も許容するのは影響が大きい気がしますが、問題ないでしょうか？
この静的解析を大本で外さなくても JSON で使用したいクラスの直前に `SuppressMessage` 属性を入れれば抑制できると思います。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +        }
プロバイダにする必要はあるのでしょうか？
最初からフィールドで `AppState` を `new` して `AppUsageLogWriter` に渡せば良いと思いました。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +        private void ClearCacheOnDev()
`HOLIDAY_PROD` シンボルを入れると `CC0091` の "Make 'ClearCacheOnDev' method static." が警告を出すと思いますが、これは抑制しなくて良いでしょうか？

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +        private readonly AppStateProvider appStateProvider = new AppStateProvider();
フィールドはクラスの冒頭にまとめた方が分かりやすいです。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +        private const string AppStageCategory = nameof(AppUsage);
フィールドはクラス冒頭にまとめた方が分かりやすいです。

またフィールド名は `AppUsageCategory` が正しいかと思ったのですが、このままで問題ないでしょうか？

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +            else if (LogLevel.Error == logLevel)
2 つの値を比較する際は左側に変数を置いて右側に定数を置いた方が分かりやすいと思います。

```CSharp
if (logCategory == AppStageCategory)
else if (logLevel == LogLevel.Error)
```

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +            var errorStatus = ErrorStatus.Of(message, exception?.StackTrace, LogType.Error, appUsageConfig);
`message` に加えて `exception.Message` も送った方がいいかと思います。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +                    }
`Hook` メソッドの前に `Where` メソッドをチェインさせるとすっきりすると思います。

```CSharp
OnErrorOccurred
    .Where(errorLog.LogType == LogType.Error || errorLog.LogType == LogType.Exception)
    .Hook(errorLog =>
        Collect(ErrorStatus.Of(errorLog.LogString, errorLog.StackTrace, errorLog.LogType, appUsageConfig)))
    .AddTo(disposables);
```

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/ErrorStatus.cs
> +        }
コンストラクタでなく静的な `Of` メソッドにしている理由が何かあるのでしょうか？

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUtils.cs
> +        public static long ToMb(long bytes) => (long)((bytes >> 10) / 1024f);
```CSharp
public static long ToMb(long bytes) => bytes >> 20;
```

で良いと思います。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/Config/AppUsageConfig.asset
> +  pushUrl: http://localhost:3100/loki/api/v1/push
外部に Grafana/Loki を立てたときにここの URL はそこへの接続情報となると思いますが、このスクリプタブルオブジェクトはプッシュして大丈夫でしょうか？

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/StageState.cs
> +        public void CountUpTextChats() => NumberOfTextChatsSent += 1;
```CSharp
public void CountUpTextChats() => NumberOfTextChatsSent++;
```

で良いと思います。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/README.md
> +    1. Select `Import`.
Select -> Click

2023-06-12 06:13 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +  read:
もう少し具体的なプロセス名を付けた方が良いと思いますがいかがでしょうか？

2023-06-12 06:13 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +          - loki
ここは何をしているのでしょうか？

2023-06-12 06:13 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +    entrypoint:
ファイルに切り出して volumes 等でマウントした方が良いと思いました。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/ErrorStatus.cs
> +                stackTrace = $"{stackTrace.Substring(0, appUsageConfig.MaxStackTraceLength)}...";
```CSharp
stackTrace.Substring(0, appUsageConfig.MaxStackTraceLength)
```

私の環境では上記の部分で `IDE0057` の「Substring を簡素化できます」という静的解析が警告を出していて、クイックフィックスを適用すると以下のようになります。

```CSharp
stackTrace[..appUsageConfig.MaxStackTraceLength]
```

このクイックフィックスを適用するか、コードはこのままにしてこの静的解析を `.editorconfig` ファイルで無効化するか、どちらが良いでしょうか？
クイックフィックス適用後は範囲演算子というものを適用した形になっており、配列に対して `[Start..End]` で Start 番目から End 番の 1 つ手前までの部分配列を取得できます。
実験してみた限りは 10 ps 未満の誤差だったので完全に好みの問題だと思っています。

2023-06-12 06:15 UTC, sus-taguchi-t commented
私の環境でのみ警告を発しているであろう静的解析の対応をしました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/3078690a5137d5bcecde3a44cc6441911df6f314

2023-06-12 06:52 UTC, kiyohome commented on .editorconfig
> +# dotnet_naming_style.disallowed_style.required_suffix = ____RULE_VIOLATION____
探したんですが、SuppressMessageの書き方が分からなかったので外しました。
やり方が分かればSuppressMessageにしましょう。

2023-06-12 06:56 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +        }
はじめはnewして渡してたんですが、AppStateの中でELoggerを使っていて、特に今回の変更でNotifyが呼ばれたときにＬogErrorを出してます。
AppStateをnewして渡すと、AppStateのみデフォルトのLogWriterが設定されてしまい、NotifyのLogErrorが意図したとおり処理されない問題が発生しました。
そのためプロバイダーを作ってAppStateをnewするタイミングをずらしつつ、AppUsageLogWriterに渡せるようにしています。

2023-06-12 06:57 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +        private readonly AppStateProvider appStateProvider = new AppStateProvider();
このあたりの静的チェックでできない部分は、統一するならルール化が必要になるので、リスクが無ければどちらでもいいことにしたいのですが、いかがでしょうか？

2023-06-12 06:57 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +            else if (LogLevel.Error == logLevel)
このあたりの静的チェックでできない部分は、統一するならルール化が必要になるので、リスクが無ければどちらでもいいことにしたいのですが、いかがでしょうか？

2023-06-12 07:06 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/ErrorStatus.cs
> +        }
強いこだわりはありませんが、フィールドに直接設定しないAppUsageConfigを渡してErrorStatusを作るための処理をしているのでOfメソッドにしました。

2023-06-12 07:09 UTC, kiyohome commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +          - loki
&xxxで変数定義して、*xxxで違う場所で参照（展開）してました。重複を取り除く際に使ってますね。
[YAML1.1で使われる記号の意味](https://qiita.com/shinkuFencer/items/63aae879dd5a7372ba7d)

2023-06-12 08:11 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +        }
ドキュメントを追記する

2023-06-12 08:12 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +        private void ClearCacheOnDev()
HOLIDAY_PRODをPRテンプレートに入れましょう。コンパイルエラーや静的チェックは見ておく。

2023-06-12 13:43 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +        private void ClearCacheOnDev()
mainに入れないとPRに出てこないのでdevelopが落ち着いたらmainに入れてdevelopをリベースします。
PBIを入れました。
https://github.com/orgs/extreal-dev/projects/1/views/1?pane=issue&itemId=30565387

2023-06-12 13:45 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +        }
コメントを入れました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/a2a9331fff0fc317a7afc9fb237b06c6efb67c14

2023-06-12 13:47 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +        private const string AppStageCategory = nameof(AppUsage);
クラス冒頭へのまとめはリスクがないので対応してません。

フィールド名は修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/f856eef2716a056a70bfa94c7e31390861b7660c

2023-06-12 13:48 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +        private void ClearCacheOnDev()
CC0091は抑制しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/3ef929471d856e517470b9a46c86b881c9c44374

2023-06-12 14:09 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +            var errorStatus = ErrorStatus.Of(message, exception?.StackTrace, LogType.Error, appUsageConfig);
追加しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/9548371a38bc3ee6930171a4b7c09db1d37de134

2023-06-12 14:10 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +                    }
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/be78dadb022e6b6ffa4af27b10fdec8d45c61d39

2023-06-12 14:11 UTC, kiyohome commented on Assets/Holiday/App/AppUtils.cs
> +        public static long ToMb(long bytes) => (long)((bytes >> 10) / 1024f);
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/4b7273719b0762ee070d08d162af5c7d1384e4a4

2023-06-12 14:25 UTC, kiyohome commented on Assets/Holiday/App/Config/AppUsageConfig.asset
> +  pushUrl: http://localhost:3100/loki/api/v1/push
プッシュしないように削除しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/da0fdf4c95509866c541a0fe88f8d477abb1af71

2023-06-12 14:26 UTC, kiyohome commented on Assets/Holiday/App/StageState.cs
> +        public void CountUpTextChats() => NumberOfTextChatsSent += 1;
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/fe73b50ac7df5974d2fe771b8e0fa51a971d9609

2023-06-12 14:28 UTC, kiyohome commented on Servers/VisualizationOfAppUsage/README.md
> +    1. Select `Import`.
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/ea1e4bcc514ef09345191d599acf718a2d24ba33

2023-06-12 14:34 UTC, kiyohome commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +  read:
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/9c538c0d96c2e76963e75f39a97f249f320568bd

2023-06-12 15:00 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/ErrorStatus.cs
> +                stackTrace = $"{stackTrace.Substring(0, appUsageConfig.MaxStackTraceLength)}...";
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/289cedd26b193a33fc512d9211f6e4e7f01e568b

2023-06-12 15:26 UTC, kiyohome commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +    entrypoint:
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/99d056f2023f619df84fb869b5419e00b6475171

2023-06-13 00:22 UTC, sus-taguchi-t commented on .editorconfig
> +# dotnet_naming_style.disallowed_style.required_suffix = ____RULE_VIOLATION____
それぞれの変数の前

```CSharp
[SuppressMessage("Usage", "IDE1006")] public string ClientId;
```

か、クラスの前

```CSharp
[SuppressMessage("", "IDE1006")]
public class AppUsageBase
```

のどちらかに書けば抑制できると思います。

2023-06-13 00:53 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +        }
確認しました。

2023-06-13 00:54 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +        private void ClearCacheOnDev()
確認しました。

2023-06-13 00:55 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +        private readonly AppStateProvider appStateProvider = new AppStateProvider();
ルール化した方がリスクが高いと思うのでこのままにしましょう。

2023-06-13 00:55 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +        private const string AppStageCategory = nameof(AppUsage);
確認しました。

2023-06-13 00:55 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +            else if (LogLevel.Error == logLevel)
ルール化した方がリスクが高いと思うのでこのままにしましょう。

2023-06-13 01:00 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageLogWriter.cs
> +            var errorStatus = ErrorStatus.Of(message, exception?.StackTrace, LogType.Error, appUsageConfig);
確認しました。

2023-06-13 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +                    }
確認しました。

2023-06-13 01:24 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/ErrorStatus.cs
> +        }
わかりました。
このままでいきましょう。

2023-06-13 01:59 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUtils.cs
> +        public static long ToMb(long bytes) => (long)((bytes >> 10) / 1024f);
確認しました。

2023-06-13 02:00 UTC, sus-taguchi-t commented on Assets/Holiday/App/Config/AppUsageConfig.asset
> +  pushUrl: http://localhost:3100/loki/api/v1/push
確認しました。

2023-06-13 02:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/StageState.cs
> +        public void CountUpTextChats() => NumberOfTextChatsSent += 1;
確認しました。

2023-06-13 02:02 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/README.md
> +    1. Select `Import`.
確認しました。

2023-06-13 02:03 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +  read:
確認しました。

2023-06-13 02:03 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +          - loki
分かりました。
ありがとうございます。

2023-06-13 02:05 UTC, sus-taguchi-t commented on Servers/VisualizationOfAppUsage/docker-compose.yaml
> +    entrypoint:
確認しました。

2023-06-13 02:11 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/ErrorStatus.cs
> +                stackTrace = $"{stackTrace.Substring(0, appUsageConfig.MaxStackTraceLength)}...";
確認しました。

2023-06-13 02:20 UTC, sus-taguchi-t requested changes

2023-06-13 02:20 UTC, sus-taguchi-t commented on Packages/manifest.json
> +    "jp.co.tis.extreal.core.common": "https://github.com/extreal-dev/Extreal.Core.Common.git#1.1.0-next.2",
`Core.Common` に新しいタグの追加と、ここの修正もお願いします。

2023-06-13 02:27 UTC, kiyohome commented on .editorconfig
> +# dotnet_naming_style.disallowed_style.required_suffix = ____RULE_VIOLATION____
変更しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/1d901c30b22a7064b70d2a11d429a720b94b7568
RiderだとRiderのチェックが残ってしまい抑制されないのですが入れました。

2023-06-13 04:12 UTC, kiyohome commented on Packages/manifest.json
> +    "jp.co.tis.extreal.core.common": "https://github.com/extreal-dev/Extreal.Core.Common.git#1.1.0-next.2",
更新しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/8/commits/fa9e0ead3a506d72c6457c11b717e4a632205773

2023-06-13 04:30 UTC, sus-taguchi-t commented on .editorconfig
> +# dotnet_naming_style.disallowed_style.required_suffix = ____RULE_VIOLATION____
確認しました。

2023-06-13 04:32 UTC, sus-taguchi-t commented on Packages/manifest.json
> +    "jp.co.tis.extreal.core.common": "https://github.com/extreal-dev/Extreal.Core.Common.git#1.1.0-next.2",
確認しました。

2023-06-13 04:33 UTC, sus-taguchi-t approved these changes

2023-06-13 04:33 UTC, merged