Refactoring AppUsage
extreal-dev/Extreal.SampleApp.Holiday pull request #9
Opened 2023-06-13 14:42 UTC by kiyohome

# 何の変更を加えましたか？

- AppUsageManagerから各利用状況毎の処理をクラスに抜き出しました。

# 何を確認しましたか?

## 実装
- [ ] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました

## テスト
- [ ] 変更影響がある全てのテストが成功することを確認しました
- [ ] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響
- [ ] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-06-15 10:29 UTC, sus-taguchi-t requested changes

2023-06-15 10:29 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +                });
各クラスを `builder` に登録して `AppUsageManager` に自動でインジェクトさせる方法もありますが、ここは各クラスは登録したくないためにこの形の実装になっているという認識であっていますでしょうか？

2023-06-15 10:29 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +        public class ErrorLog
他のクラスでも使用しているのでこのクラスは外に出した方が良いかと思いました。

2023-06-15 10:29 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +        public AppUsageConfig AppUsageConfig { get; }
これらが `public` になっているところが気になりました。
各コレクターが持っていては不都合があるのでしょうか？

2023-06-15 10:29 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +                disposables.Add(appUsageCollector.Collect(this));
各コレクタとこの `AppUsageManager` が相互参照しているのが気になります。
参照を一方向にするのはやはり難しいですかね？

2023-06-15 12:26 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +                });
はい、認識合ってます。
IAppUsageCollectorはAppUsageManagerでしか使う想定がないためRegisterしてないです。
RegisterするのはできるだけDIするものだけにしたいです。

2023-06-15 15:14 UTC, kiyohome commented
ダッシュボードに誤字があったので修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9/commits/8d752608b5a34427209f2b60b82e74a3ff97a14b

2023-06-15 15:15 UTC, kiyohome commented on Assets/Holiday/App/AppScope.cs
> +                });
全体を見直しCollectorでDIが必要になったのでRegisterするようにしました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9/commits/537cf26257996a72fb4841fed70336641813a823

2023-06-15 15:16 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +        public class ErrorLog
出しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9/commits/537cf26257996a72fb4841fed70336641813a823

2023-06-15 15:16 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +        public AppUsageConfig AppUsageConfig { get; }
privateにしました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9/commits/537cf26257996a72fb4841fed70336641813a823

2023-06-15 15:17 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +                disposables.Add(appUsageCollector.Collect(this));
一方向にしてみました、いかがでしょうか？
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9/commits/537cf26257996a72fb4841fed70336641813a823

2023-06-16 01:01 UTC, sus-taguchi-t requested changes

2023-06-16 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageEmitter.cs
> +        private readonly Subject<ErrorLog> onErrorOccured = new Subject<ErrorLog>();
Occured -> Occurred

2023-06-16 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppScope.cs
> +                });
確認しました。

2023-06-16 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +        public AppUsageConfig AppUsageConfig { get; }
確認しました。

2023-06-16 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +                disposables.Add(appUsageCollector.Collect(this));
かなりすっきりした気がします！
良いと思います！

2023-06-16 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageManager.cs
> +        public class ErrorLog
確認しました。

2023-06-16 01:01 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/ErrorLog.cs
> +    public class ErrorLog
すみません、今気づきました。
このクラスは `JsonUtility` で使用しているわけではないので、フィールドを public にしなくて良いと思います。
いままで通りカプセル化した方が良いと思います。

2023-06-16 03:25 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/AppUsageEmitter.cs
> +        private readonly Subject<ErrorLog> onErrorOccured = new Subject<ErrorLog>();
修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9/commits/579302d69bfad3389b5e63cdac7962e03754d5cd

2023-06-16 03:42 UTC, kiyohome commented on Assets/Holiday/App/AppUsage/ErrorLog.cs
> +    public class ErrorLog
修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9/commits/a88ee42bbbdd43a208b5405ea63581302f90ba43

2023-06-16 03:59 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/AppUsageEmitter.cs
> +        private readonly Subject<ErrorLog> onErrorOccured = new Subject<ErrorLog>();
確認しました。

2023-06-16 04:00 UTC, sus-taguchi-t commented on Assets/Holiday/App/AppUsage/ErrorLog.cs
> +    public class ErrorLog
確認しました。

2023-06-16 06:36 UTC, sus-taguchi-t approved these changes

2023-06-16 06:37 UTC, merged